const { JSDOM } = require("jsdom");
const fs = require("fs");
const P = require("path").resolve(__dirname, "..") + "/";
const dom = new JSDOM(fs.readFileSync(P+"docs/index.html","utf8"),{runScripts:"outside-only",url:"https://cvidal22.github.io/peerledger-workflow-toolkit/",pretendToBeVisual:true});
const w = dom.window; w.PL_DEBUG=false; w.HTMLElement.prototype.scrollIntoView=function(){};
if(!w.PointerEvent) w.PointerEvent=w.MouseEvent;
const L=f=>w.eval(fs.readFileSync(P+f,"utf8"));
L("docs/data.js"); L("docs/app.js"); L("core/pl-core.js");
const $=s=>w.document.querySelector(s), $$=s=>[...w.document.querySelectorAll(s)];
const click=el=>el.dispatchEvent(new w.MouseEvent("click",{bubbles:true}));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
  console.log("nav links:", $$(".topnav a").map(a=>a.textContent).join(" "));
  w.location.hash="#/section/reports"; await wait(150);
  console.log("stub:", $("#stub-title").textContent, "|", $("#stub-body").textContent.slice(0,50));
  w.location.hash="#/escalations"; await wait(150);
  console.log("escalations:", $("#queue-title").textContent, "rows:", $$("#queue-body tr").length, "|", $("#queue-count").textContent);
  w.location.hash="#/claim/Dispute02"; await wait(200);
  console.log("\ndeadline tag:", $("#claim-deadline").textContent, "class:", $("#claim-deadline").className);
  console.log("stage:", $("#claim-stage").textContent);
  console.log("evidence:", $("#evidence-count").textContent);
  console.log("evidence row 1:", $("#evidence-list li").textContent.replace(/\s+/g," "));
  console.log("parties:", [...$$("#complainant-kv .v")].slice(0,2).map(v=>v.textContent).join(" / "));
  console.log("note rows:", $$("#notes-table tbody tr td.by").length);
  console.log("\n-- deadline carry-forward --");
  const before=$("#deadline-current").textContent;
  click($('[data-deadline="6"]')); await wait(500);
  console.log("before:", before.replace(/\s+/g," "));
  console.log("after :", $("#deadline-current").textContent.replace(/\s+/g," "));
  console.log("\n-- recovery lifecycle --");
  click($("#recovery-open")); await wait(900);
  console.log("state:", $("#recovery-state").textContent, "| ref:", $("#recovery-ref").textContent);
  console.log("stage:", $("#claim-stage").textContent);
  click($("#recovery-settle")); await wait(800);
  console.log("settled:", $("#recovery-state").textContent);
  console.log("\n-- close then audit query reopens --");
  $("#note-input").value="Decision recorded."; click($("#note-save")); await wait(600);
  click($("#close-claim")); await wait(700);
  console.log("closed:", $("#claim-state").textContent, "| stage:", $("#claim-stage").textContent);
  console.log("audit:", $("#audit-state").textContent);
  click($("#audit-query")); await wait(700);
  console.log("after query -> state:", $("#claim-state").textContent, "| stage:", $("#claim-stage").textContent);
  console.log("note rows now:", $$("#notes-table tbody tr td.by").length);
  process.exit(0);
})();
